name: Go Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.5, 1.6, 1.7, 1.8, 1.9, 1.10, 1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.20, 1.21]
        platform: [windows, darwin, linux]
        arch: [386, amd64, arm64]
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Project
        run: |
          go build -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }} main.go
        env:
          GOOS: ${{ matrix.platform }}
          GOARCH: amd64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}
          path: ./bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Get the current date
        id: date
        run: echo "date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.date }}
          name: "Release ${{ steps.date.outputs.date }}"
          files: "./artifacts/*"