name: Go Build and Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      strategy:
        matrix:
          go-version: ["1.13", "1.14", "1.15", "1.16", "1.17", "1.18", "1.19", "1.20", "1.21"]
          platform: [windows, darwin, linux]
          arch: [386, amd64, arm64]
          strip: [true, false]
      steps:
        - name: Install Go
          uses: actions/setup-go@v5
          with:
            go-version: ${{ matrix.go-version }}
  
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Build Project
          run: |
            if ${{ matrix.strip }}; then
              go build -ldflags="-s -w" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-strip main.go
            else
              go build -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }} main.go
            fi
          env:
            GOOS: ${{ matrix.platform }}
            GOARCH: amd64
  
        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}${{ matrix.strip && '-strip' || '' }}
            path: ./bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}${{ matrix.strip && '-strip' || '' }}

    release:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Download artifacts
          uses: actions/download-artifact@v4
          with:
            path: artifacts
            merge-multiple: true
  
        - name: Create Release
          uses: softprops/action-gh-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: latest
            name: "Release"
            files: "./artifacts/*"
            prerelease: true