name: Build kubelet

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      strategy:
        matrix:
          go-version: ["1.26"]
          platform: [windows, darwin, linux]
          arch: [amd64, arm64]
          strip: [true, false]
      steps:
        - name: Install Go
          uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
          with:
            go-version: ${{ matrix.go-version }}
  
        - name: Checkout code
          uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
          with:
            repository: kubernetes/kubernetes
            fetch-depth: 1
  
        - name: Build Project
          run: |
            if ${{ matrix.strip }}; then
              go build -ldflags="-s -w" -o kubelet-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-strip ./cmd/kubelet/kubelet.go
            else
              go build -o kubelet-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }} ./cmd/kubelet/kubelet.go
            fi
          env:
            GOOS: ${{ matrix.platform }}
            GOARCH: amd64
  
        - name: Upload artifacts
          uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
          with:
            name: kubelet-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}${{ matrix.strip && '-strip' || '' }}
            path: ./kubelet-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}${{ matrix.strip && '-strip' || '' }}

    release:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Download artifacts
          uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
          with:
            path: artifacts
            merge-multiple: true
  
        - name: Create Release
          uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: kube
            name: "Release"
            files: "./artifacts/*"
            prerelease: true
