name: Build kubelet

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      strategy:
        matrix:
          go-version: ["1.24"]
          platform: [windows, darwin, linux]
          arch: [amd64, arm64]
          strip: [true, false]
      steps:
        - name: Install Go
          uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
          with:
            go-version: ${{ matrix.go-version }}
  
        - name: Checkout code
          uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
          with:
            repository: kubernetes/kubernetes
            fetch-depth: 1
  
        - name: Build Project
          run: |
            if ${{ matrix.strip }}; then
              go build -ldflags="-s -w" -o kubelet-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-strip ./cmd/kubelet/kubelet.go
            else
              go build -o kubelet-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }} ./cmd/kubelet/kubelet.go
            fi
          env:
            GOOS: ${{ matrix.platform }}
            GOARCH: amd64
  
        - name: Upload artifacts
          uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
          with:
            name: kubelet-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}${{ matrix.strip && '-strip' || '' }}
            path: ./kubelet-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}${{ matrix.strip && '-strip' || '' }}

    release:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Download artifacts
          uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
          with:
            path: artifacts
            merge-multiple: true
  
        - name: Create Release
          uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 # v2.3.3
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: kube
            name: "Release"
            files: "./artifacts/*"
            prerelease: true
