name: Build mini example

on:
  workflow_dispatch:
  push: 
    branches: master

permissions:
  contents: write

jobs:
    build:
      name: Build
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          go-version: ["1.16", "1.17", "1.18", "1.19", "1.20", "1.21"]
          arch: [386, amd64, arm64]
          include:
            - os: windows-latest
              platform: windows
            - os: macos-latest
              platform: darwin
            - os: ubuntu-latest
              platform: linux
        fail-fast: true
      steps:
        - name: Install Go
          uses: actions/setup-go@v5
          with:
            go-version: ${{ matrix.go-version }}
  
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Build Project
          run: |
            go build -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }} .
            go build -ldflags="-s -w" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-strip .
            go build -ldflags="-linkmode external" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-ext .
            go build -ldflags="-s -w -linkmode external" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-strip-ext .
          env:
            GOOS: ${{ matrix.platform }}
            GOARCH: amd64
  
        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}
            path: |
              ./bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}
              ./bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-ext
              ./bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-strip
              ./bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-strip-ext

    release:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Download artifacts
          uses: actions/download-artifact@v4
          with:
            path: artifacts
            merge-multiple: true

        - uses: dev-drprasad/delete-tag-and-release@v1.0 # PRERELEASE is v1.0 and can also be used to test and give us feedback
          with:
            tag_name: latest
            github_token: ${{ secrets.GITHUB_TOKEN }}
  
        - name: Create Release
          uses: softprops/action-gh-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: latest
            name: "Release"
            files: "./artifacts/*"
            prerelease: true