name: Build mini example

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version:
          - "1.25"
          - "1.26"
          - "1.27"
        os: [windows-2022, macos-15-intel, ubuntu-22.04, macos-14]
        include:
          - os: windows-2022
            platform: windows
          - os: macos-15-intel
            platform: darwin
          - os: macos-14
            platform: darwin
          - os: ubuntu-22.04
            platform: linux
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          check-latest: true

      - name: Setup Linux
        if: ${{ matrix.platform == 'linux' }}
        run: |
          sudo apt-fast update
          sudo apt-fast install -y gcc-aarch64-linux-gnu gcc-11-multilib
          sudo ln -s /usr/include/asm-generic /usr/include/asm

      - uses: msys2/setup-msys2@4f806de0a5a7294ffabaff804b38a9b435a73bda # v2.30.0
        if: ${{ matrix.platform == 'windows' }}
        with:
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-i686-gcc

      - name: Build binaries
        shell: bash
        run: |
          python3 scripts/build.py
        env:
          PLATFORM: ${{ matrix.platform }}
          GO_VERSION: ${{ matrix.go-version }}

      - name: Upload artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.os }}
          path: |
            ./bin-*

  build-wasm:
    name: Build wasm (${{ matrix.platform }}, Go ${{ matrix.go-version }})
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        go-version:
          - "1.25"
          - "1.26"
          - "1.27"
        platform:
          - js
          - wasip1
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          check-latest: true

      - name: Build wasm
        shell: bash
        run: |
          python3 scripts/build.py
        env:
          PLATFORM: ${{ matrix.platform }}
          GO_VERSION: ${{ matrix.go-version }}

      - name: Upload artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: bin-${{ matrix.platform }}-${{ matrix.go-version }}-ubuntu-22.04
          path: |
            ./bin-*

  release:
    needs:
      - build
      - build-wasm
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          path: artifacts
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: latest
          name: "Release"
          files: "./artifacts/*"
          prerelease: true
