name: Build mini example

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version:
          - "1.11"
          - "1.12"
          - "1.13"
          - "1.14"
          - "1.15"
          - "1.16"
          - "1.17"
          - "1.18"
          - "1.19"
          - "1.20"
          - "1.21"
          - "1.22"
        os: [windows-2022, macos-12, ubuntu-22.04, macos-14]
        include:
          - os: windows-2022
            platform: windows
          - os: macos-12
            platform: darwin
          - os: macos-14
            platform: darwin
          - os: ubuntu-22.04
            platform: linux
        exclude:
          # darwin/arm64 available from go 1.16
          - go-version: "1.11"
            os: macos-14
          - go-version: "1.12"
            os: macos-14
          - go-version: "1.13"
            os: macos-14
          - go-version: "1.14"
            os: macos-14
          - go-version: "1.15"
            os: macos-14
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
          check-latest: true

      - name: Setup Linux
        if: ${{ matrix.platform == 'linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
          sudo apt-get install gcc-multilib
      
      - uses: msys2/setup-msys2@v2
        if: ${{ matrix.platform == 'windows' }}
        with:
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-i686-gcc
            mingw-w64-clang-aarch64-gcc-compat

      - name: Build binaries
        shell: bash
        run: |
          python3 scripts/build.py
        env:
          PLATFORM: ${{ matrix.platform }}
          GO_VERSION: ${{ matrix.go-version }}

      - name: Upload artifacts
        if: ${{ github.event_name != 'push' }}
        uses: actions/upload-artifact@v4
        with:
          name: bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.os }}
          path: |
            ./bin-*

  build_old:
    name: Build old versions
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version:
          - "1.5"
          - "1.6"
          - "1.7"
          - "1.8"
          - "1.9"
          - "1.10"
        os: [windows-2019, ubuntu-20.04, macos-11]
        include:
          - os: windows-2019
            platform: windows
          - os: ubuntu-20.04
            platform: linux
          - os: macos-11
            platform: darwin
        exclude:
          - go-version: "1.5"
            os: macos-11
          - go-version: "1.6"
            os: macos-11
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
          check-latest: true
      
      - uses: msys2/setup-msys2@v2
        if: ${{ matrix.platform == 'windows' }}
        with:
          install: >-
            clang

      - name: Build binaries
        shell: bash
        run: |
          python scripts/build.py
        env:
          PLATFORM: ${{ matrix.platform }}
          GO_VERSION: ${{ matrix.go-version }}

      - name: Upload artifacts
        if: ${{ github.event_name != 'push' }}
        uses: actions/upload-artifact@v4
        with:
          name: bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.os }}
          path: |
            ./bin-*

  release:
    needs:
      - build
      - build_old
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'push' }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: latest
          name: "Release"
          files: "./artifacts/*"
          prerelease: true
