name: Build mini example

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      strategy:
        matrix:
          go-version: ["1.16", "1.17", "1.18", "1.19", "1.20", "1.21"]
          platform: [windows, darwin, linux]
          arch: [386, amd64, arm64]
      steps:
        - name: Install Go
          uses: actions/setup-go@v5
          with:
            go-version: ${{ matrix.go-version }}
  
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Build Project
          run: |
            go build -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }} .
            go build -tags "with_cgo" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-cgo .
            go build -ldflags="-s -w" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-strip .
            go build -tags "with_cgo" -ldflags="-s -w" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-strip-cgo .
            go build -ldflags="-extldflags \"-linkmode external\"" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-linker .
            go build -tags "with_cgo" -ldflags="-extldflags \"-linkmode external\"" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-cgo-linker .
            go build -ldflags="-s -w -extldflags \"-linkmode external\"" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-strip-linker .
            go build -tags "with_cgo" -ldflags="-s -w -extldflags \"-linkmode external\"" -o bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-strip-cgo-linker .
          env:
            GOOS: ${{ matrix.platform }}
            GOARCH: amd64
  
        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}
            path: |
              ./bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}
              ./bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-cgo
              ./bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-strip
              ./bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.arch }}-strip-cgo

    release:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Download artifacts
          uses: actions/download-artifact@v4
          with:
            path: artifacts
            merge-multiple: true
  
        - name: Create Release
          uses: softprops/action-gh-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: latest
            name: "Release"
            files: "./artifacts/*"
            prerelease: true