name: Build mini example

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version:
          - "1.17"
          - "1.18"
          - "1.19"
          - "1.20"
          - "1.21"
          - "1.22"
          - "1.23"
          - "1.24"
        os: [windows-2022, macos-13, ubuntu-22.04, macos-14]
        include:
          - os: windows-2022
            platform: windows
          - os: macos-13
            platform: darwin
          - os: macos-14
            platform: darwin
          - os: ubuntu-22.04
            platform: linux
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          check-latest: true

      - name: Setup Linux
        if: ${{ matrix.platform == 'linux' }}
        run: |
          sudo apt-fast update
          sudo apt-fast install -y gcc-aarch64-linux-gnu gcc-11-multilib
          sudo ln -s /usr/include/asm-generic /usr/include/asm

      - uses: msys2/setup-msys2@v2
        if: ${{ matrix.platform == 'windows' }}
        with:
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-i686-gcc

      - name: Build binaries
        shell: bash
        run: |
          python3 scripts/build.py
        env:
          PLATFORM: ${{ matrix.platform }}
          GO_VERSION: ${{ matrix.go-version }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bin-${{ matrix.platform }}-${{ matrix.go-version }}-${{ matrix.os }}
          path: |
            ./bin-*

  release:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: latest
          name: "Release"
          files: "./artifacts/*"
          prerelease: true
